// <auto-generated />
namespace NewsSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Connection_For_Album_To_AlbumCategory_And_CoverImage_Property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Connection_For_Album_To_AlbumCategory_And_CoverImage_Property));
        
        string IMigrationMetadata.Id
        {
            get { return "201510231445143_Added_Connection_For_Album_To_AlbumCategory_And_CoverImage_Property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
