// <auto-generated />
namespace NewsSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_AlbumTokensAndRelationsForTokens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_AlbumTokensAndRelationsForTokens));
        
        string IMigrationMetadata.Id
        {
            get { return "201602060647463_Added_AlbumTokensAndRelationsForTokens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
