// <auto-generated />
namespace NewsSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REMOVED_RelationBetweenCommentAndUser_AllCommentsWillBeAnonymose_ADDED_AuthorNameAndAvatarOptionsInComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REMOVED_RelationBetweenCommentAndUser_AllCommentsWillBeAnonymose_ADDED_AuthorNameAndAvatarOptionsInComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251704241_REMOVED_RelationBetweenCommentAndUser_AllCommentsWillBeAnonymose_ADDED_AuthorNameAndAvatarOptionsInComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
