// <auto-generated />
namespace NewsSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class First_MigrationShouldResetAllRealtionships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_MigrationShouldResetAllRealtionships));
        
        string IMigrationMetadata.Id
        {
            get { return "201602200641337_First_MigrationShouldResetAllRealtionships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
